---
openapi: 3.0.0
info:
  title: AtCreate API
  version: 1.0.0
servers:
  - url: https://atcreate-api.azurewebsites.net/api/
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: POST /login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: test@email.com
                password: some-secure-password
      security:
        - noauthAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /device-configs:
    get:
      tags:
        - Protected
      summary: GET /device-configs
      parameters:
        - name: all
          in: query
          schema:
            type: boolean
          example: "true"
        - name: sigfoxId
          in: query
          schema:
            type: string
          example: 7F64BE
        - name: formatted
          in: query
          schema:
            type: boolean
          example: "true"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /devices:
    get:
      tags:
        - Protected
      summary: GET /devices
      parameters:
        - name: formatted
          in: query
          schema:
            type: boolean
          example: "true"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /healthcheck:
    get:
      tags:
        - Protected
      summary: GET /healthcheck
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /sensor-depth:
    get:
      tags:
        - Protected
      summary: GET /sensor-depth
      parameters:
        - name: sensorId
          in: query
          schema:
            type: integer
          example: "1"
        - name: sigfoxId
          in: query
          schema:
            type: string
          example: 7F64BE
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /sensor-readings:
    get:
      tags:
        - Protected
      summary: GET /sensor-readings
      parameters:
        - name: sigfoxId
          in: query
          schema:
            type: string
          example: 7F6BC2
        - name: limit
          in: query
          schema:
            type: integer
          example: "5000"
        - name: fromTimestamp
          in: query
          schema:
            type: integer
          example: "1647035926"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
